# Generated by Django 4.0.1 on 2022-01-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='src_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
