# Generated by Django 4.0.1 on 2022-01-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_review_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created', '-vote_ratio', '-vote_total']},
        ),
    ]
